name: Data Processing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  submit_to_azureml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Azure ML CLI v2
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Azure ML Job
      run: |
        az extension add -n ml -y
        az ml job create --file scripts/azureml-job.yml \
          --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
          --workspace-name "${{ secrets.AZUREML_WORKSPACE_NAME }}" \
          --only-show-errors --stream
