name: Data Processing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  submit_to_azureml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies # Renamed this step for clarity
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming azure-ai-ml is in your requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run AzureML Pipeline Script # Changed step name to reflect action
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZUREML_WORKSPACE_NAME: ${{ secrets.AZUREML_WORKSPACE_NAME }}
        # Note: DATASET_NAME and DATASET_VERSION are defined within mlops.py already
        # You can remove them here or use them to override values in the script.
      run: |
        az extension add -n ml -y # It's good to keep this to ensure ml CLI extension is installed
        python scripts/MLOps.py # This is the correct command to run your pipeline
