name: Decision Tree Regressor Training Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train_and_evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-ai-ml mlflow pandas scikit-learn azureml-core

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Azure ML Job
      run: |
        az extension add -n ml -y
        az ml job create --file .azureml/job.yml \
          --workspace-name auto_ai \
          --resource-group auto_ai \
          --only-show-errors --stream
